Resources:
  SqlServerInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: sqlserver-instance
      DBInstanceClass: db.t3.micro
      Engine: sqlserver-ex
      MasterUsername: admin
      MasterUserPassword: test-test-test
      AllocatedStorage: 20
      MultiAZ: false
      PubliclyAccessible: true
      VPCSecurityGroups: [!Ref SqlServerSecurityGroup] 
      BackupRetentionPeriod: 7
      DeletionProtection: false
      LicenseModel: license-included
      DBSubnetGroupName: !Ref SqlServerSubnetGroup
 
