version: '3.5'
services:
  spring-boot-base:
    container_name: spring-boot-base
    build:
      context: .
      dockerfile: Dockerfile.dev 
    networks:
      - spring-boot-base-network
      - postgres-network
    ports:
      - 8080:8080
    volumes:
      - .:/app/spring-boot-base
      - volume-spring-boot-base-node_modules:/app/spring-boot-base/node_modules
    stdin_open: true
    tty: true
    env_file:
      - .env
volumes:
  volume-spring-boot-base-node_modules:
    name: volume-spring-boot-base-node_modules

networks:
   spring-boot-base-network:
    name: spring-boot-base-network
    driver: bridge
   postgres-network:
    name: postgres-network
    external: true
