service: spring-boot-to-do-list

provider:
  name: aws
  runtime: java21  
  region: us-east-2
  environment:
    DB_HOST: !GetAtt SqlServerInstance.Endpoint.Address
    DB_NAME: spring-boot-to-do-list
    DB_USERNAME: admin
    DB_PASSWORD: test-test-test
    LOG_LEVEL: INFO
package:
  artifact: target/spring_boot_to_do-list-0.0.1-SNAPSHOT.jar
custom:
  functionsDir: src/main/java/spring_boot_to_do_list/spring_boot_to_do_list/infra/functions
functions:
   - ${file(${self:custom.functionsDir}/api/handler.yml)}
resources:
   - "${file(devops/vpc.yml)}"
   - "${file(devops/sg.yml)}"
   - "${file(devops/db.yml)}"