spring:
  application:
    name: spring_boot_to_do-list
  logging:
    level:
      root: DEBUG
      org:
       springframework: DEBUG
  datasource:
    url: jdbc:sqlserver://sql-server;databaseName=spring-boot-to-do-list
    username: sa
    password: Sqlserver@2025
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver