spring:
  application:
    name: spring_boot_to_do-list
  logging:
    level:
      root: DEBUG
      org:
       springframework: DEBUG
  datasource:
    url: jdbc:sqlserver://sql-server;databaseName=spring-boot-to-do-list;encrypt=false
    username: sa
    password: Sqlserver@2025
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        show_sql: false
  flyway:
    enabled: false