package boilerplate_spring_boot_docker.boilerplate_spring_boot_docker.application.repositories;

import boilerplate_spring_boot_docker.boilerplate_spring_boot_docker.application.dtos.repositories.user.create.CreateUserRepositoryInputDto;

public interface UserRepositoryInterface {
  void create(CreateUserRepositoryInputDto input);
}
