name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  spring_boot:
    name: CI
    uses: GabrielSoares-Dev/workflows/.github/workflows/spring-boot-docker-portainer-CI.yml@master
    with:
      node_version: '18.*'
      java_version: '21'
