name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  spring_boot:
    name: CI
    uses: GabrielSoares-Dev/workflows/.github/workflows/spring-boot-postgres-CI.yml@master
    with:
      postgres_image: 'postgres:15.4-alpine'
      node_version: '18.*'
      java_version: '21'
      db_name: 'spring-boot-base'
