name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  spring-boot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18.*'
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'
    - name: Install Dependencies
      run: npm run install:java:dependencies
    - name: Code style check
      run: npm run lint:test
    - name: Run tests and generate coverage report
      run: npm run test:coverage