name: DEPLOY - SPRING BOOT - SERVERLESS
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
jobs:
  serverless:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "18.x"
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Install Dependencies
      run: npm run install:java:dependencies
    - name: Build project
      run: npm run build
    - name: Install Node Dependencies
      run: npm ci
    - name: Deploy
      run: npm run deploy